### ISSUE TITLE
SamFw-FRP-Tool v4.9 Windows Defender Alarm:  Virus (Trojaner) fond

### ISSUE THREAD

**Issue by WinterharteGeranienzwiebeln** [autogpttutorials/SamFw-FRP-Tool#1]
Hi, 

attention !  Virus found in  SamFw-FRP-Tool v4.9

MS Defender block the offical download link https://samfw.com/blog/samfw-frp-tool-1-0-remove-samsung-frp-one-click
![Alarm_MS_Defender](https://github.com/autogpttutorials/SamFw-FRP-Tool/assets/85982337/8cfa25ec-4a9c-4cc3-acc0-5d60c7866c09)

**Comment by droidcrafts** [comment]
Check this official note: 
Warning: The application uses several tools and scripts to unlock the device and obfuscator to protect the source code so it is suspected to be a virus. This is a false positive.
The world's leading anti-virus software such as Kaspersky, Avast, Avira, AVG... all trust and mark the application as safe.

MD5: 99b1e36598e55933e350430519b53b34

Virustotal: https://www.virustotal.com/gui/file/72b4e02b59b6cf1bfec786e2b1acf98d31cdceb906beb115b52f3bbf07e02fb3
